### ISSUE TITLE
Epic for language-tools

### ISSUE THREAD

**Issue by ashutoshmindgrep** [godspeedsystems/language-tools#12]
This is the epic for enhancement of `language-tools`.

- [x] #13 
- [ ] #14 
- [ ] #15
- [ ] #1 
- [x] #2 
- [x] #3 
- [x] #7 
- [x] #5 
- [x] #4
- [ ] figure out external ref
- [ ] testing using ajv
- [ ] Creating schema for request body, param etc based on open api spec

**Comment by Mohit-Sharma1** [comment]
get KT from rohit and update

**Comment by mastersilv3r** [comment]
@gurjotmindgrep can you please organize the information on vscode tooling, document and present to us

A. What has been so far desired to be done (list of items so far documented in the 2-3 issues on tooling assigned to you. Or anything else not documented )
 B.  What has been accomplishe - full or partially. Where is its repository? Does it have a README or some sort of documentation?
C. What stories and items remain to be done
D. How to attempt the items
E. Mark the items as a low hanging fruit or hard nut.  if you can guess, add approx effort estimation along with level of skill required.
I am adding same comments in the issue as well.
